name: CD - alb-template

on:
  push:
    branches:
      - dev-i

jobs:
  deploy:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-templates.yml@main
    with:
      cf-stack-name: "dev-stack"
