name: CD - Template Deploy

on:
  push:
    branches:
      - dev-i

jobs:
  deploy-qa:
    uses: ops-migration/central-shared-workflow/.github/workflows/cd-templates.yml@main
    with:
      aws-region: "us-east-1"
      cf-stack-name: "ecs-stack" 
